# Generated by Django 3.1.6 on 2021-02-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicos', '0004_auto_20210213_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='foto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
